include config/Makefile.nacl

NACL_ARCH := arm
CC  := arm-nacl-gcc
CXX := arm-nacl-g++
LD  := arm-nacl-g++
STRIP  := arm-nacl-strip

#WARN += -Wno-unused-but-set-variable -Wno-maybe-uninitialized
BIN_EXTENSION = _arm.nexe
EXT.DYNAMIC = so
LDFLAGS.EXTRA =
LIBDIR =
LDFLAGS.GL =
LDFLAGS.GLU = -lRegalGLU
LDFLAGS.GLUT = -lRegalGLUT
LDFLAGS.STATIC =
BIN.SUFFIX =
LIB.SONAME = lib$(NAME).so.$(SO_MAJOR)
LIB.DEVLNK = lib$(NAME).so
LIB.SHARED = lib$(NAME).so.$(SO_VERSION)
LIB.STATIC = lib$(NAME).a
